name: Stock Bot Scheduler

on:
  schedule:
    - cron: '30 23 * * *' # 매일 아침 8시 30분
  workflow_dispatch:      # 수동 실행 버튼

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v3

      - name: 파이썬 3.11 설치 (최신 버전 필수!)
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: 필수 라이브러리 설치
        run: |
          pip install pandas yfinance finance-datareader requests lxml beautifulsoup4

      - name: 봇 실행
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python main.py
